version: "3.9"
services:
  localtunnel:
    image: efrecon/localtunnel
    command:
      lt --local-host korona-service --subdomain $PROXY_DOMAIN --port 80
    links:
      - korona-service
    environment:
      - PROXY_DOMAIN
  korona-service:
    build: .
    image: korona-service:latest
    volumes:
      - ./db/:/app/db
    environment:
      - TZ
      - FLASK_SERVER_PORT
      - TELEGRAM_TOKEN
      - STORMGLASS_TOKEN
      - ALERT_TOKEN
      - AQI_TOKEN
      - API_TOKEN
      - API_LAYER_TOKEN
      - PROXY_DOMAIN
    restart: always