version: "3.9"
services:
  ngrok:
    network_mode: "host"
    image: ngrok/ngrok:latest
    restart: always
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    environment:
      - NGROK_AUTHTOKEN
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
  korona-service:
    build: .
    image: korona-service:latest
    volumes:
      - ./db/:/db
    environment:
      - TZ
      - FLASK_SERVER_PORT
      - TELEGRAM_TOKEN
      - NGROK_API_TOKEN
      - STORMGLASS_TOKEN
      - ALERT_TOKEN
      - AQI_TOKEN
      - API_TOKEN
      - API_LAYER_TOKEN
    ports:
      - 80:80
    restart: always
    depends_on:
      - ngrok