version: "3.9"
services:
  localtunnel:
    image: efrecon/localtunnel
    command:
      lt --local-host korona-service --subdomain $PROXY_DOMAIN --port 80
    environment:
      - PROXY_DOMAIN
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "Authorization: $API_TOKEN", "https://$PROXY_DOMAIN.loca.lt/tech/ping"]
      interval: 120s
      timeout: 25s
      retries: 3
    restart: always
  korona-service:
    build: .
    image: korona-service:latest
    volumes:
      - ./db/:/app/db
    environment:
      - TZ
      - FLASK_SERVER_PORT
      - TELEGRAM_TOKEN
      - STORMGLASS_TOKEN
      - ALERT_TOKEN
      - AQI_TOKEN
      - API_TOKEN
      - API_LAYER_TOKEN
      - PROXY_DOMAIN
    restart: always
    depends_on:
      - localtunnel